// src/core/ is the pure engine: framework-agnostic TypeScript, zero DOM/Svelte/platform
// imports — ever. This barrel is core's public face; app code imports only from here.
export * from './tiles'
export * from './rng'
export * from './wall'
export * from './dora'
export * from './deal'
export * from './record'
export * from './seatview'
export * from './legal'
export * from './policy'
export * from './agari'
export * from './waits'
export * from './shanten'
export * from './yaku'
export * from './yakuman'
export * from './fu'
export * from './han'
export * from './settlement'
export * from './game'
export * from './notation'
